[package]
name = "aqs_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }

[lib]
name = "aqs_analysis"
path = "src/lib.rs"

[[bin]]
name = "aqs_analysis"
path = "src/main.rs"